config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :comments
  end
  resources :admin_sessions
  root controller: 'books', action: 'index'
end

app/models/admin.rb
class Admin < ApplicationRecord
    acts_as_authentic
end

app/models/admin_session.rb
class AdminSession < Authlogic::Session::Base
    # specify configuration here, such as:
    # logout_on_timeout true
    # ...many more options in the documentation
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :book
  end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController
    def new
      @admin_session = AdminSession.new
    end
  
    def create
      @admin_session = AdminSession.new((admin_params))
      if @admin_session.save
        flash[:notice] = "Login successful!"
        redirect_to books_path
      else
        flash[:notice] = "Login was not successful!"
        render :action => :new
      end
    end
  
    def destroy
      current_admin_session.destroy
      flash[:notice] = "Logout successful!"
      redirect_to books_path
    end
  
    private
  
    def admin_params
      params.require(:admin_session).permit(:login, :password)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper :all # include all helpers, all the time
    protect_from_forgery  with: :exception # See ActionController::RequestForgeryProtection for details
  
    private
  
    def current_admin_session
      return @current_admin_session if defined?(@current_admin_session)
      @current_admin_session = AdminSession.find
    end
  
    def current_admin
      return @current_admin if defined?(@current_admin)
      @current_admin = current_admin_session && current_admin_session.admin
    end
  
    helper_method :current_admin_session, :current_admin
  end

app/controllers/books_controller.rb
class BooksController < ApplicationController 
    before_filter :login_required, except: [:index, :show]
  

    def index
    #  @books = Book.all # instance variables are prefixed with an @.
      # If we said books = Book.all, we wouldn't be able to access books in the template
      @books = Book.paginate page: params[:page], per_page: 10
    end
    def show
      @book = Book.find(params[:id])
      @comments = @book.comments.paginate(page: params[:page], per_page: 10).order('created_at ASC')
    end

    def new
      @book = Book.new
    end
    
    def create
      @book = Book.new book_params
      if @book.save
        flash[:notice] = "#{@book.title} saved."
        redirect_to @book
      else
        render :new
      end
    end
    def edit
      @book = Book.find params[:id]
    end
    
    def update
      @book = Book.find params[:id]
      if @book.update_attributes(book_params)
        flash[:notice] = "#{@book.title} saved."
        redirect_to @book
      else
        render :edit
      end
    end
    
    def destroy
      book = Book.find params[:id]
      book.destroy
      flash[:notice] = "#{book.title} deleted."
      redirect_to books_path
    end

    def login_required
      unless current_admin
        flash[:error] = 'Only logged in admins an access this page.'
        redirect_to books_path
      end
    end

    private
    
    def book_params
      params.require(:book).permit(:title, :thoughts)
    end

  end

  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      book = Book.find params[:book_id]
      comment = book.comments.new comment_params
      comment.save
      flash[:notice] = 'Comment saved'
      redirect_to book_path(book)
    end
  
    private
      # Using a private method to encapsulate the permissible parameters
      # is just a good pattern since you'll be able to reuse the same
      # permit list between create and update. Also, you can specialize
      # this method with per-user checking of permissible attributes.
      def comment_params
        params.require(:comment).permit(:author, :text)
      end
  end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin_sessions/new.html.erb
<h1>Login</h1>

<div class="col-sm-4">
  <%= form_for @admin_session do |f| %>
    <% if @admin_session.errors.any? %>
      <div class="panel panel-warning errors">
        <div class="panel-heading">
          <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
        </div>

        <ul class="panel-body">
          <% @admin_session.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :login %>
      <%= f.text_field :login, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <%= f.submit "Login", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/books/edit.html.erb
<h1>Editing <%= @book.title %></h1>

<div class="col-sm-4">
  <%= form_for(@book) do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :thoughts %>
      <%= form.text_area :thoughts, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<h1>Books</h1>

<% for book in @books do %>
  <h2><%= link_to book.title, books_path(book) %></h2>
  <%= simple_format(truncate(book.thoughts, lenght: 100)) %>
<% end %>

<%= will_paginate @books %>

<% if current_admin %>
  <p>
    Admin actions: <%= link_to 'New Book', new_book_path %>
  </p>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>

<div class="col-sm-4">
  <%= form_for(@book) do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :thoughts %>
      <%= form.text_area :thoughts, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<%= simple_format @book.thoughts %>

<% if @comments %>
  <h3>Comments</h3>

  <% for comment in @comments do %>
    <p><strong><%= comment.author %></strong>:</p>
    <%= simple_format comment.text %>
  <% end %>

  <%= will_paginate @comments %>
<% end %>

<h3>Post Your Comment</h3>
<div class="col-sm-4">
  <%= form_for([@book, Comment.new]) do |form| %>
    <div class="form-group">
      <p><%= form.label :author %></p>
      <p><%= form.text_field :author, class: 'form-control' %></p>
    </div>

    <div class="form-group">
      <p><%= form.label :text, 'Comment' %></p>
      <p><%= form.text_area :text, class: 'form-control' %></p>
    </div>
    <div class="form-group">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <% if current_admin %>
  <p>
    Admin Actions:
    <%= link_to 'Edit', edit_book_path(@book) %> |
    <%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: "Are you sure?"} %>
  </p>
  <% end %>
  
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>

    <% if current_admin %>
      <p><%= link_to 'Logout', admin_session_path(current_admin_session), method: :delete %></p>
      <% else %>
      <p><%= link_to 'Login', new_admin_session_path %></p>
      <% end %>
    </div>
</body>
</html>